site_name: Elgentos - Prismic IO Magento 2 module
site_description: Prismic IO Developer documentation

repo_name: elgentos/magento2-prismicio
repo_url: https://github.com/elgentos/magento2-prismicio

copyright: Copyright &copy; elgentos 2019-present. All rights reserved.
#site_url: ''
nav:
  - Introduction: index.md
  - Basics:
    - Installation: basics/installation.md
    - Configuration: basics/configuration.md
    - Content types: basics/content-types.md
  - Frontend:
    - Layout handles: layout/handles.md
    - Debug: layout/debug.md
    - Content: layout/content.md
    - Template: layout/template.md
    - Slices: layout/slices.md
    - Static blocks: layout/static-blocks.md
    - Document Links: layout/document-links.md
    - Alternate languages: layout/alternate-languages.md
  - Advanced:
    - Routing: advanced/routing.md
    - Routes: advanced/routes-admin.md
    - Multi-repo: advanced/multi-repo.md
    - Sitemap: advanced/sitemap.md
    - Integration fields: advanced/integration-fields.md
    - Webhooks: advanced/webhooks.md
  - Technical description:
    - Blocks:
      - Prismic fields: technical/blocks/prismic-fields.md
      - Metadata: technical/blocks/title-and-metadata.md
      - Container: technical/blocks/container.md
      - Overview: technical/blocks/overview.md
    - Console: technical/console-commands.md
    - ViewModels: technical/viewmodels.md
    - Preview mode: technical/preview-mode.md
    - Exceptions: technical/exceptions.md
    - Registry: technical/registry.md
    - Renderer: technical/renderer.md
  - Best Practices: best-practices.md
#  - Changelog: changelog.md
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/elgentos
theme:
  name: material
  features:
#    - navigation.tabs
    - navigation.top
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html


